import os
DATA_FOLDER = "data/"
RAW_DATA_FOLDER = os.path.join(DATA_FOLDER, "raw/")
PROCESSED_DATA_FOLDER = os.path.join(DATA_FOLDER, "processed/")
START_YEAR = 2014
END_YEAR = 2023
DEFAULT_FILE_NAME_WEATHER_DATA = ""